/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsProjectIdSalonesRouteImport } from './routes/projects/$projectId/salones'
import { Route as ProjectsProjectIdMateriasRouteImport } from './routes/projects/$projectId/materias'
import { Route as ProjectsProjectIdConfiguracionRouteImport } from './routes/projects/$projectId/configuracion'
import { Route as ProjectsProjectIdColaboradoresRouteImport } from './routes/projects/$projectId/colaboradores'
import { Route as ProjectsProjectIdGroupsIndexRouteImport } from './routes/projects/$projectId/groups/index'
import { Route as ProjectsProjectIdGroupsGroupIdRouteImport } from './routes/projects/$projectId/groups/$groupId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdSalonesRoute =
  ProjectsProjectIdSalonesRouteImport.update({
    id: '/projects/$projectId/salones',
    path: '/projects/$projectId/salones',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdMateriasRoute =
  ProjectsProjectIdMateriasRouteImport.update({
    id: '/projects/$projectId/materias',
    path: '/projects/$projectId/materias',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdConfiguracionRoute =
  ProjectsProjectIdConfiguracionRouteImport.update({
    id: '/projects/$projectId/configuracion',
    path: '/projects/$projectId/configuracion',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdColaboradoresRoute =
  ProjectsProjectIdColaboradoresRouteImport.update({
    id: '/projects/$projectId/colaboradores',
    path: '/projects/$projectId/colaboradores',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdGroupsIndexRoute =
  ProjectsProjectIdGroupsIndexRouteImport.update({
    id: '/projects/$projectId/groups/',
    path: '/projects/$projectId/groups/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdGroupsGroupIdRoute =
  ProjectsProjectIdGroupsGroupIdRouteImport.update({
    id: '/projects/$projectId/groups/$groupId',
    path: '/projects/$projectId/groups/$groupId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/colaboradores': typeof ProjectsProjectIdColaboradoresRoute
  '/projects/$projectId/configuracion': typeof ProjectsProjectIdConfiguracionRoute
  '/projects/$projectId/materias': typeof ProjectsProjectIdMateriasRoute
  '/projects/$projectId/salones': typeof ProjectsProjectIdSalonesRoute
  '/projects/$projectId/groups/$groupId': typeof ProjectsProjectIdGroupsGroupIdRoute
  '/projects/$projectId/groups/': typeof ProjectsProjectIdGroupsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/colaboradores': typeof ProjectsProjectIdColaboradoresRoute
  '/projects/$projectId/configuracion': typeof ProjectsProjectIdConfiguracionRoute
  '/projects/$projectId/materias': typeof ProjectsProjectIdMateriasRoute
  '/projects/$projectId/salones': typeof ProjectsProjectIdSalonesRoute
  '/projects/$projectId/groups/$groupId': typeof ProjectsProjectIdGroupsGroupIdRoute
  '/projects/$projectId/groups': typeof ProjectsProjectIdGroupsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/colaboradores': typeof ProjectsProjectIdColaboradoresRoute
  '/projects/$projectId/configuracion': typeof ProjectsProjectIdConfiguracionRoute
  '/projects/$projectId/materias': typeof ProjectsProjectIdMateriasRoute
  '/projects/$projectId/salones': typeof ProjectsProjectIdSalonesRoute
  '/projects/$projectId/groups/$groupId': typeof ProjectsProjectIdGroupsGroupIdRoute
  '/projects/$projectId/groups/': typeof ProjectsProjectIdGroupsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/projects/'
    | '/projects/$projectId/colaboradores'
    | '/projects/$projectId/configuracion'
    | '/projects/$projectId/materias'
    | '/projects/$projectId/salones'
    | '/projects/$projectId/groups/$groupId'
    | '/projects/$projectId/groups/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/projects'
    | '/projects/$projectId/colaboradores'
    | '/projects/$projectId/configuracion'
    | '/projects/$projectId/materias'
    | '/projects/$projectId/salones'
    | '/projects/$projectId/groups/$groupId'
    | '/projects/$projectId/groups'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/projects/'
    | '/projects/$projectId/colaboradores'
    | '/projects/$projectId/configuracion'
    | '/projects/$projectId/materias'
    | '/projects/$projectId/salones'
    | '/projects/$projectId/groups/$groupId'
    | '/projects/$projectId/groups/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsProjectIdColaboradoresRoute: typeof ProjectsProjectIdColaboradoresRoute
  ProjectsProjectIdConfiguracionRoute: typeof ProjectsProjectIdConfiguracionRoute
  ProjectsProjectIdMateriasRoute: typeof ProjectsProjectIdMateriasRoute
  ProjectsProjectIdSalonesRoute: typeof ProjectsProjectIdSalonesRoute
  ProjectsProjectIdGroupsGroupIdRoute: typeof ProjectsProjectIdGroupsGroupIdRoute
  ProjectsProjectIdGroupsIndexRoute: typeof ProjectsProjectIdGroupsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/salones': {
      id: '/projects/$projectId/salones'
      path: '/projects/$projectId/salones'
      fullPath: '/projects/$projectId/salones'
      preLoaderRoute: typeof ProjectsProjectIdSalonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/materias': {
      id: '/projects/$projectId/materias'
      path: '/projects/$projectId/materias'
      fullPath: '/projects/$projectId/materias'
      preLoaderRoute: typeof ProjectsProjectIdMateriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/configuracion': {
      id: '/projects/$projectId/configuracion'
      path: '/projects/$projectId/configuracion'
      fullPath: '/projects/$projectId/configuracion'
      preLoaderRoute: typeof ProjectsProjectIdConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/colaboradores': {
      id: '/projects/$projectId/colaboradores'
      path: '/projects/$projectId/colaboradores'
      fullPath: '/projects/$projectId/colaboradores'
      preLoaderRoute: typeof ProjectsProjectIdColaboradoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/groups/': {
      id: '/projects/$projectId/groups/'
      path: '/projects/$projectId/groups'
      fullPath: '/projects/$projectId/groups/'
      preLoaderRoute: typeof ProjectsProjectIdGroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/groups/$groupId': {
      id: '/projects/$projectId/groups/$groupId'
      path: '/projects/$projectId/groups/$groupId'
      fullPath: '/projects/$projectId/groups/$groupId'
      preLoaderRoute: typeof ProjectsProjectIdGroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsProjectIdColaboradoresRoute: ProjectsProjectIdColaboradoresRoute,
  ProjectsProjectIdConfiguracionRoute: ProjectsProjectIdConfiguracionRoute,
  ProjectsProjectIdMateriasRoute: ProjectsProjectIdMateriasRoute,
  ProjectsProjectIdSalonesRoute: ProjectsProjectIdSalonesRoute,
  ProjectsProjectIdGroupsGroupIdRoute: ProjectsProjectIdGroupsGroupIdRoute,
  ProjectsProjectIdGroupsIndexRoute: ProjectsProjectIdGroupsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
